from .service import AuthService, InitDataError